server {
    listen 80;
    server_name kknubt.id;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name kknubt.id;

    ssl_certificate     /etc/letsencrypt/live/kknubt.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kknubt.id/privkey.pem;
    include             /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/kkn-ubt/public;
    index index.php;
    charset utf-8;

    client_max_body_size 50M;

    error_page 413 /errors/413;

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location = /errors/413 {
        try_files /index.php?$query_string /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
